const ROLE_LABELS={administrator:"管理员",hr_specialist:"HR / 招聘专员",interviewer:"面试官",hiring_manager:"部门负责人 / 用人经理"};
const JOB_STORAGE_KEY="rs_jobs_v012";
const FILTERS_DEFAULT={keyword:"",module:"",operationType:"",operatorName:"",objectType:"",result:"",source:"",dateFrom:"",dateTo:""};
const state={me:null,filters:{...FILTERS_DEFAULT},logs:[],activeLogId:"",usingFallbackData:false};
const els={currentUser:document.getElementById("operations-current-user"),logoutBtn:document.getElementById("operations-logout-btn"),filterKeyword:document.getElementById("operations-filter-keyword"),filterModule:document.getElementById("operations-filter-module"),filterType:document.getElementById("operations-filter-type"),filterUser:document.getElementById("operations-filter-user"),filterObjectType:document.getElementById("operations-filter-object-type"),filterResult:document.getElementById("operations-filter-result"),filterSource:document.getElementById("operations-filter-source"),filterFrom:document.getElementById("operations-filter-from"),filterTo:document.getElementById("operations-filter-to"),filterResetBtn:document.getElementById("operations-filter-reset-btn"),exportJsonBtn:document.getElementById("operations-export-json-btn"),exportCsvBtn:document.getElementById("operations-export-csv-btn"),exportDetailBtn:document.getElementById("operations-export-detail-btn"),exportMessage:document.getElementById("operations-export-message"),statTotal:document.getElementById("operations-stat-total"),statSuccess:document.getElementById("operations-stat-success"),statFailed:document.getElementById("operations-stat-failed"),statModule:document.getElementById("operations-stat-module"),listMeta:document.getElementById("operations-list-meta"),logList:document.getElementById("operations-log-list"),detailMeta:document.getElementById("operations-detail-meta"),detailResult:document.getElementById("operations-detail-result"),emptyDetail:document.getElementById("operations-empty-detail"),detailBody:document.getElementById("operations-detail-body"),detailSummary:document.getElementById("operations-detail-summary"),highlightList:document.getElementById("operations-highlight-list"),detailLogId:document.getElementById("detail-log-id"),detailOperationModule:document.getElementById("detail-operation-module"),detailOperationType:document.getElementById("detail-operation-type"),detailObjectType:document.getElementById("detail-object-type"),detailObjectId:document.getElementById("detail-object-id"),detailObjectName:document.getElementById("detail-object-name"),detailOperatorId:document.getElementById("detail-operator-id"),detailOperatorName:document.getElementById("detail-operator-name"),detailOperatedAt:document.getElementById("detail-operated-at"),detailOperationResult:document.getElementById("detail-operation-result"),detailClientIp:document.getElementById("detail-client-ip"),detailRequestSource:document.getElementById("detail-request-source"),detailRemark:document.getElementById("detail-remark"),compareMeta:document.getElementById("operations-compare-meta"),compareEmpty:document.getElementById("operations-compare-empty"),compareList:document.getElementById("operations-compare-list"),detailExtraContext:document.getElementById("detail-extra-context")};

function redirectToLogin(force=false){window.location.href=force?"/login?force=1":"/login";}
async function fetchJSON(url,options={}){const req={...options};if(req.body){req.headers={"Content-Type":"application/json",...(req.headers||{})};}const resp=await fetch(url,req);let data={};try{data=await resp.json();}catch{data={};}if(!resp.ok){const err=new Error(data.error||"请求失败");err.status=resp.status;throw err;}return data;}
function roleCodeFromUser(user){const role=String(user?.role_code||"").trim().toLowerCase();if(role){return role;}return Number(user?.is_admin||0)===1?"administrator":"hr_specialist";}
function roleLabelFromUser(user){return ROLE_LABELS[roleCodeFromUser(user)]||"用户";}
function canAccessOperationLogs(user){return roleCodeFromUser(user)==="administrator";}
function formatTime(value){if(!value){return "-";}const date=new Date(value);return Number.isNaN(date.getTime())?String(value||"-"):date.toLocaleString("zh-CN",{hour12:false});}
function formatDateValue(value){if(!value){return "";}const date=new Date(value);return Number.isNaN(date.getTime())?"":date.toISOString().slice(0,10);}
function fillSelect(select,options,blankLabel){if(!select){return;}select.innerHTML=[`<option value="">${blankLabel}</option>`].concat(options.map((item)=>`<option value="${item}">${item}</option>`)).join("");}
function setExportMessage(text,kind=""){if(!els.exportMessage){return;}els.exportMessage.textContent=text;els.exportMessage.className="form-message";if(kind){els.exportMessage.classList.add(kind);}}
function normalizeLog(item){return{log_id:String(item?.log_id||"").trim(),operation_module:String(item?.operation_module||"").trim(),operation_type:String(item?.operation_type||"").trim(),biz_object_type:String(item?.biz_object_type||"").trim(),biz_object_id:String(item?.biz_object_id||"").trim(),biz_object_name:String(item?.biz_object_name||"").trim(),operator_user_id:String(item?.operator_user_id||"").trim(),operator_name:String(item?.operator_name||"").trim(),operated_at:String(item?.operated_at||"").trim(),operation_result:String(item?.operation_result||"").trim()||"success",client_ip:String(item?.client_ip||"").trim()||"-",request_source:String(item?.request_source||"").trim()||"前端演示",remark:String(item?.remark||"").trim(),extra_context:item?.extra_context&&typeof item.extra_context==="object"?item.extra_context:{}};}
function readJobsFromStorage(){try{const parsed=JSON.parse(window.localStorage.getItem(JOB_STORAGE_KEY)||"[]");return Array.isArray(parsed)?parsed:[];}catch{return [];}}
function mapJobActionToOperationType(action){const text=String(action||"");if(text.includes("创建")){return"create";}if(text.includes("更新")){return"update";}if(text.includes("关闭")){return"close";}if(text.includes("复制")){return"copy";}if(text.includes("触发")){return"trigger";}if(text.includes("切换")){return"activate";}return"audit";}
function buildJobLogs(){return readJobsFromStorage().flatMap((job)=>{const logs=Array.isArray(job.logs)?job.logs:[];return logs.map((log)=>normalizeLog({log_id:log.log_id,operation_module:"岗位管理",operation_type:mapJobActionToOperationType(log.action),biz_object_type:"job",biz_object_id:job.job_id,biz_object_name:job.title||job.job_code||"未命名岗位",operator_name:log.operator||"未知用户",operated_at:log.at,operation_result:"success",client_ip:"-",request_source:"岗位页本地日志",remark:log.detail||log.action||"",extra_context:{legacy_action:String(log.action||""),job_code:String(job.job_code||""),status:String(job.status||"")}}));}).filter((item)=>item.log_id&&item.biz_object_id);}
function buildDemoLogs(){const name=String(state.me?.display_name||state.me?.username||"管理员");const uid=String(state.me?.id||"");const now=Date.now();return[{log_id:"demo_log_001",operation_module:"用户与权限",operation_type:"update",biz_object_type:"user",biz_object_id:"user_alice",biz_object_name:"Alice",operator_user_id:uid,operator_name:name,operated_at:new Date(now-18*60*1000).toISOString(),operation_result:"success",client_ip:"127.0.0.1",request_source:"用户管理页",remark:"更新用户角色，并同步校验部门范围。",extra_context:{changed_fields:["role_code","department_scope"],role_after:"hr_specialist"}},{log_id:"demo_log_002",operation_module:"候选人管理",operation_type:"update",biz_object_type:"candidate",biz_object_id:"candidate_zhangsan",biz_object_name:"张三",operator_user_id:uid,operator_name:name,operated_at:new Date(now-42*60*1000).toISOString(),operation_result:"success",client_ip:"127.0.0.1",request_source:"工作台",remark:"维护候选人基础信息并更新申请岗位。",extra_context:{changed_fields:["school_name","highest_education","applied_position"]}},{log_id:"demo_log_003",operation_module:"流程流转",operation_type:"transition",biz_object_type:"candidate_stage",biz_object_id:"candidate_zhangsan_stage_1",biz_object_name:"张三 / 初筛 -> 一面",operator_user_id:uid,operator_name:name,operated_at:new Date(now-65*60*1000).toISOString(),operation_result:"success",client_ip:"127.0.0.1",request_source:"工作台",remark:"候选人从初筛推进到一面。",extra_context:{changed_fields:["from_stage","to_stage"],from_stage:"初筛",to_stage:"一面"}},{log_id:"demo_log_004",operation_module:"自动评分",operation_type:"trigger",biz_object_type:"candidate_score",biz_object_id:"score_candidate_zhangsan",biz_object_name:"张三 / 自动评分",operator_user_id:uid,operator_name:name,operated_at:new Date(now-95*60*1000).toISOString(),operation_result:"failed",client_ip:"127.0.0.1",request_source:"工作台",remark:"手动触发自动评分失败，保留异常示例。",extra_context:{changed_fields:["operation_result","reason"],reason:"llm_timeout"}},{log_id:"demo_log_005",operation_module:"系统使用",operation_type:"login",biz_object_type:"session",biz_object_id:"session_demo_001",biz_object_name:"管理员登录",operator_user_id:uid,operator_name:name,operated_at:new Date(now-130*60*1000).toISOString(),operation_result:"success",client_ip:"127.0.0.1",request_source:"登录页",remark:"管理员登录系统并进入工作台。",extra_context:{changed_fields:["request_source"],user_agent:"frontend-demo"}}].map((item)=>normalizeLog(item));}
function buildFallbackLogs(){return buildDemoLogs().concat(buildJobLogs()).filter((item)=>item.log_id).sort((a,b)=>Date.parse(b.operated_at||"")-Date.parse(a.operated_at||""));}
function buildQuery(filters,format=""){const params=new URLSearchParams();if(filters.keyword){params.set("keyword",filters.keyword);}if(filters.module){params.set("module",filters.module);}if(filters.operationType){params.set("operation_type",filters.operationType);}if(filters.operatorName){params.set("operator_name",filters.operatorName);}if(filters.objectType){params.set("biz_object_type",filters.objectType);}if(filters.result){params.set("operation_result",filters.result);}if(filters.source){params.set("request_source",filters.source);}if(filters.dateFrom){params.set("operated_from",filters.dateFrom);}if(filters.dateTo){params.set("operated_to",filters.dateTo);}if(format){params.set("format",format);}return params.toString();}
function collectUniqueValues(field){return Array.from(new Set(state.logs.map((item)=>String(item[field]||"").trim()).filter(Boolean))).sort((a,b)=>a.localeCompare(b,"zh-CN"));}
function syncFilterOptions(){fillSelect(els.filterModule,collectUniqueValues("operation_module"),"全部模块");fillSelect(els.filterType,collectUniqueValues("operation_type"),"全部类型");fillSelect(els.filterUser,collectUniqueValues("operator_name"),"全部操作人");fillSelect(els.filterObjectType,collectUniqueValues("biz_object_type"),"全部对象类型");fillSelect(els.filterResult,collectUniqueValues("operation_result"),"全部结果");fillSelect(els.filterSource,collectUniqueValues("request_source"),"全部来源");}
function syncFiltersToInputs(){els.filterKeyword.value=state.filters.keyword;els.filterModule.value=state.filters.module;els.filterType.value=state.filters.operationType;els.filterUser.value=state.filters.operatorName;els.filterObjectType.value=state.filters.objectType;els.filterResult.value=state.filters.result;els.filterSource.value=state.filters.source;els.filterFrom.value=state.filters.dateFrom;els.filterTo.value=state.filters.dateTo;}
function readFiltersFromInputs(){state.filters={keyword:String(els.filterKeyword.value||"").trim(),module:String(els.filterModule.value||"").trim(),operationType:String(els.filterType.value||"").trim(),operatorName:String(els.filterUser.value||"").trim(),objectType:String(els.filterObjectType.value||"").trim(),result:String(els.filterResult.value||"").trim(),source:String(els.filterSource.value||"").trim(),dateFrom:String(els.filterFrom.value||"").trim(),dateTo:String(els.filterTo.value||"").trim()};}
function filteredLogs(){const keyword=state.filters.keyword.toLowerCase();return state.logs.filter((item)=>{if(state.filters.module&&item.operation_module!==state.filters.module){return false;}if(state.filters.operationType&&item.operation_type!==state.filters.operationType){return false;}if(state.filters.operatorName&&item.operator_name!==state.filters.operatorName){return false;}if(state.filters.objectType&&item.biz_object_type!==state.filters.objectType){return false;}if(state.filters.result&&item.operation_result!==state.filters.result){return false;}if(state.filters.source&&item.request_source!==state.filters.source){return false;}if(state.filters.dateFrom&&formatDateValue(item.operated_at)<state.filters.dateFrom){return false;}if(state.filters.dateTo&&formatDateValue(item.operated_at)>state.filters.dateTo){return false;}if(!keyword){return true;}return[item.log_id,item.biz_object_name,item.biz_object_id,item.operator_name,item.remark,item.operation_module,item.operation_type,item.request_source].join(" ").toLowerCase().includes(keyword);});}
function resultLabel(result){if(result==="success"){return"成功";}if(result==="failed"){return"失败";}return result||"-";}
function pickTopModule(logs){if(!logs.length){return"-";}const counts=new Map();logs.forEach((item)=>counts.set(item.operation_module,(counts.get(item.operation_module)||0)+1));let name="-";let count=-1;counts.forEach((value,key)=>{if(value>count){name=key;count=value;}});return name;}
function setDetailValue(el,value){if(el){el.textContent=String(value||"-");}}
function valuePreview(value){if(Array.isArray(value)){return value.join(", ");}if(value&&typeof value==="object"){return JSON.stringify(value);}if(value===null||value===undefined||value===""){return"-";}return String(value);}
function highlightFieldsForLog(item){const fields=Array.isArray(item?.extra_context?.changed_fields)?item.extra_context.changed_fields:[];const extra=[];if(item?.operation_result==="failed"){extra.push("operation_result");}if(item?.request_source){extra.push("request_source");}return Array.from(new Set(fields.concat(extra).filter(Boolean)));}
function findComparableLog(item){if(!item?.biz_object_id){return null;}const currentTime=Date.parse(item.operated_at||"");return state.logs.find((candidate)=>{if(candidate.log_id===item.log_id||candidate.biz_object_id!==item.biz_object_id){return false;}const time=Date.parse(candidate.operated_at||"");return!Number.isNaN(time)&&time<currentTime;})||null;}
function compareFieldRows(current,previous){const keys=Array.from(new Set(["operation_module","operation_type","biz_object_name","operator_name","operation_result","request_source"].concat(highlightFieldsForLog(current)).concat(Object.keys(current?.extra_context||{})).concat(Object.keys(previous?.extra_context||{}))));return keys.map((key)=>{const currentValue=Object.prototype.hasOwnProperty.call(current?.extra_context||{},key)?current.extra_context[key]:current?.[key];const previousValue=Object.prototype.hasOwnProperty.call(previous?.extra_context||{},key)?previous.extra_context[key]:previous?.[key];return{key,currentValue:valuePreview(currentValue),previousValue:valuePreview(previousValue),changed:valuePreview(currentValue)!==valuePreview(previousValue)};}).filter((row)=>row.changed);}
function renderStats(logs){els.statTotal.textContent=String(logs.length);els.statSuccess.textContent=String(logs.filter((item)=>item.operation_result==="success").length);els.statFailed.textContent=String(logs.filter((item)=>item.operation_result==="failed").length);els.statModule.textContent=pickTopModule(logs);}
function renderList(logs){els.logList.innerHTML="";const suffix=state.usingFallbackData?"（当前展示前端演示 / 本地聚合数据）":"";els.listMeta.textContent=`共 ${state.logs.length} 条记录，当前命中 ${logs.length} 条${suffix}`;if(!logs.length){const li=document.createElement("li");li.className="operations-log-empty";li.textContent="暂无匹配的操作记录，请调整筛选条件。";els.logList.appendChild(li);return;}logs.forEach((item)=>{const li=document.createElement("li");li.className=`operations-log-item ${item.log_id===state.activeLogId?"active":""}`;li.innerHTML=`<div class="operations-log-top"><div><div class="operations-log-title">${item.biz_object_name||item.log_id}</div><div class="operations-log-meta">${item.operation_module} · ${item.operation_type} · ${formatTime(item.operated_at)}</div></div><span class="operations-result-badge ${item.operation_result==="failed"?"failed":"success"}">${resultLabel(item.operation_result)}</span></div><div class="operations-log-tags"><span class="tag">${item.biz_object_type||"-"}</span><span class="tag">${item.request_source||"-"}</span><span class="tag">${item.operator_name||"-"}</span></div><p class="operations-log-remark">${item.remark||"暂无备注说明"}</p>`;li.addEventListener("click",()=>{state.activeLogId=item.log_id;renderPage();void loadLogDetailFromServer(item.log_id);});els.logList.appendChild(li);});}
function renderHighlights(item){els.highlightList.innerHTML="";const fields=highlightFieldsForLog(item);if(!fields.length){const span=document.createElement("span");span.className="operations-highlight-empty";span.textContent="当前记录未标记关键变更字段。";els.highlightList.appendChild(span);return;}fields.forEach((field)=>{const span=document.createElement("span");span.className="operations-highlight-chip";span.textContent=field;els.highlightList.appendChild(span);});}
function renderCompareSection(item){const previous=findComparableLog(item);els.compareList.innerHTML="";if(!previous){els.compareMeta.textContent="未找到可比对记录";els.compareEmpty.textContent="当前记录暂无同对象上一条操作可供比对。";els.compareEmpty.classList.remove("hidden");els.compareList.classList.add("hidden");return;}const rows=compareFieldRows(item,previous);els.compareMeta.textContent=`对比同对象上一条记录：${previous.log_id} · ${formatTime(previous.operated_at)}`;if(!rows.length){els.compareEmpty.textContent="已找到上一条记录，但当前数据中未识别出可展示差异。";els.compareEmpty.classList.remove("hidden");els.compareList.classList.add("hidden");return;}els.compareEmpty.classList.add("hidden");els.compareList.classList.remove("hidden");rows.forEach((row)=>{const article=document.createElement("article");article.className="operations-compare-item";article.innerHTML=`<div class="operations-compare-key">${row.key}</div><div class="operations-compare-values"><div class="operations-compare-value previous"><span class="operations-compare-label">上一条</span><code>${row.previousValue}</code></div><div class="operations-compare-value current"><span class="operations-compare-label">当前</span><code>${row.currentValue}</code></div></div>`;els.compareList.appendChild(article);});}
function renderDetail(item){if(!item){els.emptyDetail.classList.remove("hidden");els.detailBody.classList.add("hidden");els.detailMeta.textContent="请选择一条记录查看详情";els.detailResult.textContent="-";els.detailResult.className="operations-result-badge";els.highlightList.innerHTML="";els.compareMeta.textContent="未找到可比对记录";els.compareEmpty.textContent="当前记录暂无同对象上一条操作可供比对。";els.compareEmpty.classList.remove("hidden");els.compareList.classList.add("hidden");els.compareList.innerHTML="";els.detailExtraContext.textContent="-";return;}els.emptyDetail.classList.add("hidden");els.detailBody.classList.remove("hidden");els.detailMeta.textContent=`${item.operation_module} · ${formatTime(item.operated_at)}`;els.detailResult.textContent=resultLabel(item.operation_result);els.detailResult.className=`operations-result-badge ${item.operation_result==="failed"?"failed":"success"}`;els.detailSummary.textContent=`${item.operator_name||"未知操作人"} 对 ${item.biz_object_name||item.biz_object_id||"业务对象"} 执行了 ${item.operation_type||"操作"}，结果为 ${resultLabel(item.operation_result)}。`;setDetailValue(els.detailLogId,item.log_id);setDetailValue(els.detailOperationModule,item.operation_module);setDetailValue(els.detailOperationType,item.operation_type);setDetailValue(els.detailObjectType,item.biz_object_type);setDetailValue(els.detailObjectId,item.biz_object_id);setDetailValue(els.detailObjectName,item.biz_object_name);setDetailValue(els.detailOperatorId,item.operator_user_id);setDetailValue(els.detailOperatorName,item.operator_name);setDetailValue(els.detailOperatedAt,formatTime(item.operated_at));setDetailValue(els.detailOperationResult,resultLabel(item.operation_result));setDetailValue(els.detailClientIp,item.client_ip);setDetailValue(els.detailRequestSource,item.request_source);setDetailValue(els.detailRemark,item.remark);renderHighlights(item);renderCompareSection(item);els.detailExtraContext.textContent=JSON.stringify(item.extra_context||{},null,2);}
function renderCurrentUser(){if(!state.me){els.currentUser.textContent="未登录";return;}const displayName=state.me.display_name||state.me.username||"当前用户";els.currentUser.textContent=`当前用户：${displayName} (@${state.me.username}) · ${roleLabelFromUser(state.me)}`;}
function renderPage(){const logs=filteredLogs();if(!logs.some((item)=>item.log_id===state.activeLogId)){state.activeLogId=logs[0]?.log_id||"";}renderStats(logs);renderList(logs);renderDetail(logs.find((item)=>item.log_id===state.activeLogId)||null);}
function downloadBlob(filename,blob){const url=window.URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=filename;document.body.appendChild(link);link.click();link.remove();window.URL.revokeObjectURL(url);}
function downloadTextFile(filename,content,mimeType){downloadBlob(filename,new Blob([content],{type:mimeType}));}
function parseFilenameFromDisposition(value){const text=String(value||"").trim();if(!text){return"";}const match=text.match(/filename=\"([^\"]+)\"/i)||text.match(/filename=([^;]+)/i);return match?decodeURIComponent(String(match[1]||"").trim()):"";}
function exportLogsAsJson(logs){downloadTextFile(`operations-${new Date().toISOString().slice(0,19).replace(/[:T]/g,"-")}.json`,JSON.stringify(logs,null,2),"application/json;charset=utf-8");setExportMessage(`已导出 ${logs.length} 条筛选结果（JSON）。`,"success");}
function csvCell(value){return`"${String(value??"").replace(/\"/g,'""')}"`;}
function exportLogsAsCsv(logs){const header=["log_id","operation_module","operation_type","biz_object_type","biz_object_id","biz_object_name","operator_user_id","operator_name","operated_at","operation_result","client_ip","request_source","remark"];const rows=logs.map((item)=>header.map((key)=>csvCell(item[key])).join(","));downloadTextFile(`operations-${new Date().toISOString().slice(0,19).replace(/[:T]/g,"-")}.csv`,[header.join(","),...rows].join("\n"),"text/csv;charset=utf-8");setExportMessage(`已导出 ${logs.length} 条筛选结果（CSV）。`,"success");}
function exportCurrentDetail(){const item=state.logs.find((log)=>log.log_id===state.activeLogId);if(!item){setExportMessage("请先选择一条记录后再导出详情。","error");return;}downloadTextFile(`${item.log_id||"operation-detail"}.json`,JSON.stringify(item,null,2),"application/json;charset=utf-8");setExportMessage(`已导出当前详情：${item.log_id}`,"success");}
async function loadLogDetailFromServer(logId){if(state.usingFallbackData||!logId){return;}try{const data=await fetchJSON(`/api/operation-logs/${encodeURIComponent(logId)}`);const item=normalizeLog(data.item||{});if(!item.log_id){return;}state.logs=state.logs.map((log)=>log.log_id===item.log_id?item:log);if(state.activeLogId===item.log_id){renderPage();}}catch{}}
async function refreshLogsFromServer(){readFiltersFromInputs();try{const query=buildQuery(state.filters);const data=await fetchJSON(`/api/operation-logs${query?`?${query}`:""}`);state.logs=Array.isArray(data.items)?data.items.map((item)=>normalizeLog(item)):[];state.usingFallbackData=false;setExportMessage("");}catch(err){if(err.status===401){redirectToLogin(false);return;}if(err.status===403){window.location.href="/";return;}state.logs=buildFallbackLogs();state.usingFallbackData=true;setExportMessage("后端日志服务暂不可用，已回退到前端演示 / 本地聚合数据。","error");}syncFilterOptions();syncFiltersToInputs();renderPage();}
async function exportLogsFromServer(format){readFiltersFromInputs();if(state.usingFallbackData){if(format==="csv"){exportLogsAsCsv(filteredLogs());}else{exportLogsAsJson(filteredLogs());}return;}try{const query=buildQuery(state.filters,format);const resp=await fetch(`/api/operation-logs/export${query?`?${query}`:""}`);if(!resp.ok){let message="导出失败";try{const payload=await resp.json();message=payload.error||message;}catch{}const err=new Error(message);err.status=resp.status;throw err;}const blob=await resp.blob();const filename=parseFilenameFromDisposition(resp.headers.get("Content-Disposition"))||`operation-logs.${format}`;downloadBlob(filename,blob);setExportMessage(`已发起当前筛选结果导出（${format.toUpperCase()}）。`,"success");}catch(err){if(err.status===401){redirectToLogin(false);return;}setExportMessage(err.message||"导出失败","error");}}
async function resetFilters(){state.filters={...FILTERS_DEFAULT};syncFiltersToInputs();await refreshLogsFromServer();}
async function ensureAuthenticated(){try{const data=await fetchJSON("/api/auth/me");state.me=data.item||null;if(!state.me){redirectToLogin(false);return false;}if(Number(state.me.must_change_password||0)===1){redirectToLogin(true);return false;}if(!canAccessOperationLogs(state.me)){window.location.href="/";return false;}return true;}catch(err){if(err.status===401){redirectToLogin(false);return false;}throw err;}}
async function logout(){try{await fetchJSON("/api/auth/logout",{method:"POST"});}catch{}redirectToLogin(false);}
let keywordTimer=0;
els.logoutBtn.addEventListener("click",()=>{void logout();});
els.filterResetBtn.addEventListener("click",()=>{void resetFilters();});
els.filterKeyword.addEventListener("input",()=>{window.clearTimeout(keywordTimer);keywordTimer=window.setTimeout(()=>{void refreshLogsFromServer();},250);});
["filterModule","filterType","filterUser","filterObjectType","filterResult","filterSource","filterFrom","filterTo"].forEach((key)=>{els[key].addEventListener("change",()=>{void refreshLogsFromServer();});});
els.exportJsonBtn.addEventListener("click",()=>{void exportLogsFromServer("json");});
els.exportCsvBtn.addEventListener("click",()=>{void exportLogsFromServer("csv");});
els.exportDetailBtn.addEventListener("click",exportCurrentDetail);
(async()=>{try{const ok=await ensureAuthenticated();if(!ok){return;}renderCurrentUser();syncFiltersToInputs();await refreshLogsFromServer();}catch(err){els.listMeta.textContent=err.message||"加载失败";els.logList.innerHTML='<li class="operations-log-empty">操作记录页面初始化失败，请稍后重试。</li>';}})();
